name: Build Apache Gluten

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ maven git

      - name: Clone Apache Gluten
        run: |
          # TODO: clone specific tag
          git clone https://github.com/apache/incubator-gluten.git
          cd incubator-gluten

      - name: Build Apache Gluten
        env:
          MAVEN_ARGS: "-Pdelta"
        run: |
          ./dev/buildbundle-veloxbe.sh --enable_s3=true --spark_version=3.5
